// app/components/Navbar.vue
<script setup>
import { onClickOutside } from "@vueuse/core"

const router = useRouter();
const checked = ref(false);
const target = ref(null);

onClickOutside(target, () => { checked.value = false; });
router.afterEach(() => { checked.value = false; });
</script>

<template>
    <div class="header hstack">
        <h1>
            <NuxtLink href="/">JakeIsMeh</NuxtLink>
        </h1>

        <nav class="site-nav" ref="target">
            <!-- TODO: redo responsive navbar with focus-within -->
            <input type="checkbox" id="nav-trigger" class="nav-trigger" v-model="checked" />
            <label for="nav-trigger">
                <Icon name="ph:list-bold" class="menu-icon"/>
            </label>
            <div class="trigger">
                <NuxtLink class="nav-link" href="/about">about</NuxtLink>
                <NuxtLink class="nav-link" href="/projects">projects
                </NuxtLink>
                <NuxtLink class="nav-link" :class="{ active: $route.fullPath.startsWith('/musings') }" href="/musings">musings
                </NuxtLink>
            </div>
        </nav>
    </div>
</template>

<style lang="scss" scoped>
.header {
    justify-content: space-between;
    align-items: center;
}

h1>a {
    text-decoration: none;

    &,
    &:visited {
        color: var(--t-text);
    }

    &:hover,
    &:focus {
        background-color: unset;
        color: var(--t-text);
    }
}

.header {
    margin-bottom: $half-spacing-unit;
    border-bottom: 0.0625rem solid var(--t-text);
    padding: $quarter-spacing-unit 0;
}

h1 {
    display: inline;
}

.site-nav {
    font-family: $header-font-family;
    float: right;

    .nav-trigger {
        display: none;
    }

    .menu-icon {
        display: none;
    }

    .nav-link {
        // text-decoration: none;
        font-size: 1.25em;
        color: var(--t-text);
        font-weight: bold;
        transition: color 0.16s, background-color 0.16s;
        padding: 0 0.25em;
        margin: 0; // reset app.scss margin

        &:hover,
        &:focus,
        &.active,
        &[aria-current]:not([aria-current="false"]) {
            color: var(--t-bg);
            background-color: var(--t-text);
        }
    }

    .trigger {
        display: flex;
        gap: $half-spacing-unit;
    }

    @include media-query($on-palm) {
        position: absolute;
        top: $half-spacing-unit + $quarter-spacing-unit;
        right: $half-spacing-unit;
        background-color: var(--t-bg);
        border: 2px solid var(--t-text);
        border-radius: $radius;
        text-align: right;

        label[for='nav-trigger'] {
            display: block;
            float: right;
            width: 2.25rem;
            height: 2.25rem;
            z-index: 2;
            cursor: pointer;
        }

        .menu-icon {
            display: block;
            padding: 5px;
            margin: 3px;
            fill: currentColor;
        }

        input~.trigger {
            min-width: unset;
            min-height: unset;
            clear: both;
            display: none;
            transition: display 200ms;
        }

        input:checked~.trigger {
            display: block;
        }

        .nav-link {
            display: block;
            padding: 5px 10px;
            border-radius: 0;
        }

        a:last-of-type {
            border-radius: 0 0 ($radius - 3px) ($radius - 3px);
        }

    }
}
</style>

// src/lib/navbar.svelte
<div class="header">
    <h1><a href="/">JakeIsMeh</a></h1>

    <nav class="site-nav">
        <!-- TODO: redo responsive navbar with focus-within -->
        <input type="checkbox" id="nav-trigger" class="nav-trigger" />
        <label for="nav-trigger">
            <span class="menu-icon">
                <svg width="18px" height="15px">
                    <path
                        d="M18,1.5c0,.8-.7,1.5-1.5,1.5h-15C.7,3,0,2.3,0,1.5S.7,0,1.5,0h15c.8,0,1.5.7,1.5,1.5zm0,6c0,.8-.7,1.5-1.5,1.5h-15C.7,9,0,8.3,0,7.5S.7,6,1.5,6h15c.8,0,1.5.7,1.5,1.5zm0,6c0,.8-.7,1.5-1.5,1.5h-15C.7,15,0,14.3,0,13.5S.7,12,1.5,12h15c.8,0,1.5.7,1.5,1.5z"
                    />
                </svg>
            </span>
        </label>
        <div class="trigger">
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link" href="/about/">About</a>
            <a class="nav-link" href="/projects/">Projects</a>
        </div>
    </nav>
</div>

<style lang="scss">
    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    h1 > a {
        text-decoration: none;
        &,
        &:visited {
            transition: 0.16s;
            color: $text-color;
        }
        &:hover,
        &:focus {
            background-color: unset;
            color: $text-color;
        }
    }
    .header {
        margin-bottom: $quarter-spacing-unit;
        border-bottom: 1px solid $text-color;
    }

    h1 {
        display: inline;
    }

    .site-nav {
        font-family: $header-font-family;
        float: right;
        margin-right: -.3125em; // compensate padded link (.25em @ 1.25em)

        .nav-trigger {
            display: none;
        }

        .menu-icon {
            display: none;
        }

        .nav-link {
            font-size: 1.25em;
            color: $text-color;
            font-weight: bold;
            transition: .16s;
            padding: 0 .25em;
            margin: 0; // reset app.scss margin

            // Gaps between nav items, but not on the last one
            &:not(:last-child) {
                margin-right: .75rem;
            }

            &:hover,
            &:focus {
                color: $background-color;
                background-color: $text-color;
            }
        }

        @include media-query($on-palm) {
            position: absolute;
            top: $half-spacing-unit;
            right: $half-spacing-unit;
            background-color: $background-color;
            border: 1px solid $text-color;
            border-radius: $radius;
            text-align: right;

            label[for='nav-trigger'] {
                display: block;
                float: right;
                width: 2.25rem;
                height: 2.25rem;
                z-index: 2;
                cursor: pointer;
            }

            .menu-icon {
                display: block;
                float: right;
                width: 2.25rem;
                height: 2.25rem;
                line-height: 0;
                text-align: center;

                > svg {
                    margin-top: 10px;
                    fill: $text-color;
                }
            }

            input ~ .trigger {
                min-width: unset;
                min-height: unset;
                clear: both;
                display: none;
            }

            input:checked ~ .trigger {
                display: block;
                padding-bottom: 5px;
            }

            .nav-link {
                display: block;
                padding: 5px 10px;

                // cancel the earlier rule
                &:not(:last-child) {
                    margin-right: 0;
                }
            }
        }
    }
</style>
